### ISSUE TITLE
bindAll cannot work with getter

### ISSUE THREAD

**Issue by zaaack** [steelsojka/lodash-decorators#24]
e.g.

```js
import bindAll from 'lodash-decorators/bindAll'
@bindAll()
class A {
  get aa() {console.log('aa', this)}
  bb() {console.log('bb', this)}
}
let a = new A()
a.aa
a.bb.call(null)
```
errors:
```
aa A {}
/Users/z/Projects/Douban/share/design/assets/node_modules/lodash-decorators/bindAll.js:56
                    value: utils_1.copyMetadata(instance[key].bind(instance), instance[key]),
                                                             ^

TypeError: Cannot read property 'bind' of undefined
    at bindAllMethods (/Users/z/Projects/Douban/share/design/assets/node_modules/lodash-decorators/src/bindAll.ts:52:44)
    at A.BindAllWrapper (/Users/z/Projects/Douban/share/design/assets/node_modules/lodash-decorators/src/bindAll.ts:29:7)
    at Object.<anonymous> (/Users/z/Projects/Douban/share/design/assets/test.js:7:9)
    at Module._compile (module.js:541:32)
    at loader (/Users/z/.config/yarn/global/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/z/.config/yarn/global/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
[Finished in 3.889s]
```

**Comment by steelsojka** [comment]
Fixed 08fa50b9d4b0d336c90ea347400f79148b0d2d43. v4.3.2
